[package]
name = "API-Call"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web3 = "0.15"  # Check for the latest version
tokio = { version = "0.2.0", features = ["full"] }
dotenv = "0.15"